### ISSUE TITLE
Move the repository to an organization

### ISSUE THREAD

**Issue by critiqjo** [dbgx/lldb.nvim#48]
For some time, I've been wanting to transfer the maintainership to anyone else who is interested enough, due to lack of time in my hands. At the same time, I imagine that a common wrapper API can be developed for debugger extensions in general. So toward those ends, I believe creating an organization would be the right action to take for now.

I just created [dbgx](https://github.com/dbgx) org and am planning to move the repository to it by the end of May. If anyone has any comments or suggestions, please raise it here.

**Comment by nfnty** [comment]
It will probably not change much, but seems like a good idea. Problem for me is that I'm only using this plugin intermittently, which unfortunately makes my contributions quite scarce. Bringing on more good people would be great though.

Don't forget to add a good description and picture to the org.

**Comment by critiqjo** [comment]
For the logo, how about a horizontally symmetric pixelated image very similar to the one automatically generated by Github, except for a single pixel being a different color -- a "bug"?

And for the description, well, I'm not really the articulate type, so I could use some help. :sweat_smile:

**Comment by nfnty** [comment]
It's nicer to have something that doesn't look like a GitHub generated logo, but if you can make it stand out, then go for it. :)

Well, right now the plugin only works for Vim, but if the intention is to make something more generic in the future, then just describe it as "Debugger plugins for editors".

**Comment by critiqjo** [comment]
Kinda like this: <img src="https://cloud.githubusercontent.com/assets/1436441/24399663/14abd9b2-13cb-11e7-913d-072aadec4372.png" width=96px />

> Well, right now the plugin only works for Vim, but if the intention is to make something more generic in the future, then just describe it as "Debugger plugins for editors".

Yeah, that was my intention, even though I may not be able to contribute anything for a long time. When I named it "dbgx," what I had in mind was "Debugger extensions," but that kinda sounds like "extensions for debugger" but what I'm intending is of course "Text editor extensions for debugging." The kind of repositories I might expect are, for instance, ["Debug Adapters"](https://code.visualstudio.com/docs/extensionAPI/api-debugging) for GDB/LLDB , which talks to text editors using "VS Code Debug Protocol", and Vim/Neovim front-ends which can understand VS Code Debug Protocol.

**Comment by critiqjo** [comment]
I'll move this repository to [`dbgx`](https://github.com/dbgx) one week from now, on 18th May. I'll then create a fork to maintain the original link, with a notice pointing to the new location.

**Comment by critiqjo** [comment]
Done!
