### ISSUE TITLE
It do not accept LL commands. and then happened EventLoopError.

### ISSUE THREAD

**Issue by qwerty2501** [dbgx/lldb.nvim#52]
Hi 
I recently installed this plugin for debugging rust.
But it did not work.
here's my process:
```
LLsession new
LLmode debug( and process launch)
Then execute some LL commands ( LL r, LL c , etc...)
```
But some LL commands does'nt  work. and I can't see any responses.
Furthermore, EventLoopError happened when LL commands are executed about 3 times to 4 times.

here's error message.
```
error caught in async handler 'exec ('continue',)'
Traceback (most recent call last):
  File "/home/qwerty2501/.cache/dein/repos/github.com/critiqjo/lldb.nvim/rplugin/python/lldb_nvim/__init_
_.py", line 49, in _exec
    self.ctrl.safe_execute(args)
  File "/home/qwerty2501/.cache/dein/repos/github.com/critiqjo/lldb.nvim/rplugin/python/lldb_nvim/control
ler.py", line 101, in safe_execute
    self.safe_call(self.exec_command, [cmd])
  File "/home/qwerty2501/.cache/dein/repos/github.com/critiqjo/lldb.nvim/rplugin/python/lldb_nvim/control
ler.py", line 94, in safe_call
    raise EventLoopError("Dead event loop!")
EventLoopError: Dead event loop!
```

My environments:
OS : Ubuntu 17.0.4
neovim:0.1.7
python:2.7

**Comment by critiqjo** [comment]
I don't maintain this project anymore. See https://github.com/critiqjo/lldb.nvim/issues/51#issuecomment-294894345

**Comment by qwerty2501** [comment]
OK. I understand.

**Comment by torpak** [comment]
I have the same Problem. Does anyone have a workaround?

**Comment by johncf** [comment]
Likely to be an upstream bug. Reopen the issue if @qwerty2501 can verify it not to be. (See [this](https://github.com/dbgx/lldb.nvim/blob/master/ISSUE_TEMPLATE.md) for details)
