### ISSUE TITLE
After installation, LL commands are not recognized

### ISSUE THREAD

**Issue by kevinkjt2000** [dbgx/lldb.nvim#56]
I used Vundle to install this plugin, but LLsession is not recognized as an editor command when I open a cpp file that I compiled as part of `clang++ -std=c++14 -Wall -Wextra -pedantic -g -glldb *.cpp`

Running `:command` shows that no LL commands are registered.  Is this plugin not compatible with Vundle?

Edit: Forgot to mention I am running neovim v0.2.2

**Comment by johncf** [comment]
Did you run `:UpdateRemotePlugins` after installation?

**Comment by kevinkjt2000** [comment]
Of course not :)
